package com.bbs.pojo;

import java.util.Date;

public class Consumption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.conId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer conid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.serviceName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String servicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.conMoney
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer conmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.conJobid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer conjobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.conCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date concreatetime;
    
    private String conjobname;
    
	public String getConjobname() {
		return conjobname;
	}

	public void setConjobname(String conjobname) {
		this.conjobname = conjobname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.conId
     *
     * @return the value of consumption.conId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getConid() {
        return conid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.conId
     *
     * @param conid the value for consumption.conId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setConid(Integer conid) {
        this.conid = conid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.serviceName
     *
     * @return the value of consumption.serviceName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.serviceName
     *
     * @param servicename the value for consumption.serviceName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.conMoney
     *
     * @return the value of consumption.conMoney
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getConmoney() {
        return conmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.conMoney
     *
     * @param conmoney the value for consumption.conMoney
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setConmoney(Integer conmoney) {
        this.conmoney = conmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.conJobid
     *
     * @return the value of consumption.conJobid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getConjobid() {
        return conjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.conJobid
     *
     * @param conjobid the value for consumption.conJobid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setConjobid(Integer conjobid) {
        this.conjobid = conjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.conCreatetime
     *
     * @return the value of consumption.conCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getConcreatetime() {
        return concreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumption.conCreatetime
     *
     * @param concreatetime the value for consumption.conCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setConcreatetime(Date concreatetime) {
        this.concreatetime = concreatetime;
    }
}