package com.bbs.pojo;

import java.util.Date;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.typeCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String typecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.typeName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.valueId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer valueid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.valueNmae
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String valuenmae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.createTime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.typeCode
     *
     * @return the value of dictionary.typeCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.typeCode
     *
     * @param typecode the value for dictionary.typeCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.typeName
     *
     * @return the value of dictionary.typeName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.typeName
     *
     * @param typename the value for dictionary.typeName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.valueId
     *
     * @return the value of dictionary.valueId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getValueid() {
        return valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.valueId
     *
     * @param valueid the value for dictionary.valueId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setValueid(Integer valueid) {
        this.valueid = valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.valueNmae
     *
     * @return the value of dictionary.valueNmae
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getValuenmae() {
        return valuenmae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.valueNmae
     *
     * @param valuenmae the value for dictionary.valueNmae
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setValuenmae(String valuenmae) {
        this.valuenmae = valuenmae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.createTime
     *
     * @return the value of dictionary.createTime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.createTime
     *
     * @param createtime the value for dictionary.createTime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}