package com.bbs.pojo;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer memid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String memcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memPassword
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer mempassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String memname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memPhone
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String memphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memCreatestaid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer memcreatestaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date memcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memModifyby
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer memmodifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memModefytime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date memmodefytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memBalance
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer membalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memStatus
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer memstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memHeadpath
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String memheadpath;

    private String memstatusname;
    
    public String getMemstatusname() {
		return memstatusname;
	}

	public void setMemstatusname(String memstatusname) {
		this.memstatusname = memstatusname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memId
     *
     * @return the value of member.memId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getMemid() {
        return memid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memId
     *
     * @param memid the value for member.memId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemid(Integer memid) {
        this.memid = memid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memCode
     *
     * @return the value of member.memCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getMemcode() {
        return memcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memCode
     *
     * @param memcode the value for member.memCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemcode(String memcode) {
        this.memcode = memcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memPassword
     *
     * @return the value of member.memPassword
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getMempassword() {
        return mempassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memPassword
     *
     * @param mempassword the value for member.memPassword
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMempassword(Integer mempassword) {
        this.mempassword = mempassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memName
     *
     * @return the value of member.memName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getMemname() {
        return memname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memName
     *
     * @param memname the value for member.memName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemname(String memname) {
        this.memname = memname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memPhone
     *
     * @return the value of member.memPhone
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getMemphone() {
        return memphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memPhone
     *
     * @param memphone the value for member.memPhone
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemphone(String memphone) {
        this.memphone = memphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memCreatestaid
     *
     * @return the value of member.memCreatestaid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getMemcreatestaid() {
        return memcreatestaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memCreatestaid
     *
     * @param memcreatestaid the value for member.memCreatestaid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemcreatestaid(Integer memcreatestaid) {
        this.memcreatestaid = memcreatestaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memCreatetime
     *
     * @return the value of member.memCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getMemcreatetime() {
        return memcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memCreatetime
     *
     * @param memcreatetime the value for member.memCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemcreatetime(Date memcreatetime) {
        this.memcreatetime = memcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memModifyby
     *
     * @return the value of member.memModifyby
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getMemmodifyby() {
        return memmodifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memModifyby
     *
     * @param memmodifyby the value for member.memModifyby
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemmodifyby(Integer memmodifyby) {
        this.memmodifyby = memmodifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memModefytime
     *
     * @return the value of member.memModefytime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getMemmodefytime() {
        return memmodefytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memModefytime
     *
     * @param memmodefytime the value for member.memModefytime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemmodefytime(Date memmodefytime) {
        this.memmodefytime = memmodefytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memBalance
     *
     * @return the value of member.memBalance
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getMembalance() {
        return membalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memBalance
     *
     * @param membalance the value for member.memBalance
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMembalance(Integer membalance) {
        this.membalance = membalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memStatus
     *
     * @return the value of member.memStatus
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getMemstatus() {
        return memstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memStatus
     *
     * @param memstatus the value for member.memStatus
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemstatus(Integer memstatus) {
        this.memstatus = memstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memHeadpath
     *
     * @return the value of member.memHeadpath
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getMemheadpath() {
        return memheadpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memHeadpath
     *
     * @param memheadpath the value for member.memHeadpath
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setMemheadpath(String memheadpath) {
        this.memheadpath = memheadpath;
    }
}