package com.bbs.pojo;

import java.util.Date;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer staid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String stacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staPassword
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer stapassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String staname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staSex
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer stasex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staPhone
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String staphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.stajob
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer stajob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staAddress
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String staaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staStatus
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer stastatus;
    
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date stacreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staModifydate
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date stamodifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staId
     *
     * @return the value of staff.staId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    
    /**
     * 头像地址
     * */
    private String staHeadpath;
    
    public String getStaHeadpath() {
		return staHeadpath;
	}

	public void setStaHeadpath(String staHeadpath) {
		this.staHeadpath = staHeadpath;
	}

    
    public Integer getStaid() {
        return staid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staId
     *
     * @param staid the value for staff.staId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStaid(Integer staid) {
        this.staid = staid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staCode
     *
     * @return the value of staff.staCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getStacode() {
        return stacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staCode
     *
     * @param stacode the value for staff.staCode
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStacode(String stacode) {
        this.stacode = stacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staPassword
     *
     * @return the value of staff.staPassword
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getStapassword() {
        return stapassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staPassword
     *
     * @param stapassword the value for staff.staPassword
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStapassword(Integer stapassword) {
        this.stapassword = stapassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staName
     *
     * @return the value of staff.staName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getStaname() {
        return staname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staName
     *
     * @param staname the value for staff.staName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStaname(String staname) {
        this.staname = staname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staSex
     *
     * @return the value of staff.staSex
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getStasex() {
        return stasex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staSex
     *
     * @param stasex the value for staff.staSex
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStasex(Integer stasex) {
        this.stasex = stasex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staPhone
     *
     * @return the value of staff.staPhone
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getStaphone() {
        return staphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staPhone
     *
     * @param staphone the value for staff.staPhone
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStaphone(String staphone) {
        this.staphone = staphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.stajob
     *
     * @return the value of staff.stajob
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getStajob() {
        return stajob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.stajob
     *
     * @param stajob the value for staff.stajob
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStajob(Integer stajob) {
        this.stajob = stajob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staAddress
     *
     * @return the value of staff.staAddress
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getStaaddress() {
        return staaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staAddress
     *
     * @param staaddress the value for staff.staAddress
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStaaddress(String staaddress) {
        this.staaddress = staaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staStatus
     *
     * @return the value of staff.staStatus
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getStastatus() {
        return stastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staStatus
     *
     * @param stastatus the value for staff.staStatus
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStastatus(Integer stastatus) {
        this.stastatus = stastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staCreatetime
     *
     * @return the value of staff.staCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getStacreatetime() {
        return stacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staCreatetime
     *
     * @param stacreatetime the value for staff.staCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStacreatetime(Date stacreatetime) {
        this.stacreatetime = stacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staModifydate
     *
     * @return the value of staff.staModifydate
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getStamodifydate() {
        return stamodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staModifydate
     *
     * @param stamodifydate the value for staff.staModifydate
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setStamodifydate(Date stamodifydate) {
        this.stamodifydate = stamodifydate;
    }
}