package com.bbs.pojo;

import java.util.Date;

public class Vipconsumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.vipId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer vipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.vipNum
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer vipnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.vipName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String vipname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.vipMoney
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Integer vipmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.serviceName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private String servicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.vipJobid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Long vipjobid;
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipconsumer.vipCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    private Date vipcreatetime;

    private String vipstatus;
    
    private String memstatusname;
    
    private String vipjobname;
    
    private String staname;
    
    
	

	public Long getVipjobid() {
		return vipjobid;
	}

	public void setVipjobid(Long vipjobid) {
		this.vipjobid = vipjobid;
	}

	public String getStaname() {
		return staname;
	}

	public void setStaname(String staname) {
		this.staname = staname;
	}

	public String getMemstatusname() {
		return memstatusname;
	}

	public void setMemstatusname(String memstatusname) {
		this.memstatusname = memstatusname;
	}

	public String getVipjobname() {
		return vipjobname;
	}

	public void setVipjobname(String vipjobname) {
		this.vipjobname = vipjobname;
	}

	public String getVipstatus() {
		return vipstatus;
	}

	public void setVipstatus(String vipstatus) {
		this.vipstatus = vipstatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.vipId
     *
     * @return the value of vipconsumer.vipId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getVipid() {
        return vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipconsumer.vipId
     *
     * @param vipid the value for vipconsumer.vipId
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setVipid(Integer vipid) {
        this.vipid = vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.vipNum
     *
     * @return the value of vipconsumer.vipNum
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getVipnum() {
        return vipnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipconsumer.vipNum
     *
     * @param vipnum the value for vipconsumer.vipNum
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setVipnum(Integer vipnum) {
        this.vipnum = vipnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.vipName
     *
     * @return the value of vipconsumer.vipName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getVipname() {
        return vipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipconsumer.vipName
     *
     * @param vipname the value for vipconsumer.vipName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setVipname(String vipname) {
        this.vipname = vipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.vipMoney
     *
     * @return the value of vipconsumer.vipMoney
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Integer getVipmoney() {
        return vipmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipconsumer.vipMoney
     *
     * @param vipmoney the value for vipconsumer.vipMoney
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setVipmoney(Integer vipmoney) {
        this.vipmoney = vipmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.serviceName
     *
     * @return the value of vipconsumer.serviceName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipconsumer.serviceName
     *
     * @param servicename the value for vipconsumer.serviceName
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.vipJobid
     *
     * @return the value of vipconsumer.vipJobid
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipconsumer.vipCreatetime
     *
     * @return the value of vipconsumer.vipCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public Date getVipcreatetime() {
        return vipcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipconsumer.vipCreatetime
     *
     * @param vipcreatetime the value for vipconsumer.vipCreatetime
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    public void setVipcreatetime(Date vipcreatetime) {
        this.vipcreatetime = vipcreatetime;
    }
}