package com.bbs.mapper;

import com.bbs.pojo.Consumption;

public interface ConsumptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int deleteByPrimaryKey(Integer conid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insert(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insertSelective(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    Consumption selectByPrimaryKey(Integer conid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKeySelective(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKey(Consumption record);
}