package com.bbs.mapper;

import com.bbs.pojo.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int deleteByPrimaryKey(Integer memid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    Member selectByPrimaryKey(Integer memid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKey(Member record);
}