package com.bbs.mapper;

import java.util.List;


import com.bbs.pojo.Service;

import com.bbs.pojo.Staff;

public interface StaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int deleteByPrimaryKey(Integer staid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    Staff selectByPrimaryKey(Integer staid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKey(Staff record);
    
    //会员登录
    Staff findBy(Staff record);

    
    List<Service> sta();

    //查询职工名字
    List<Staff> staname();

    
}