package com.bbs.mapper;

import java.util.List;

import com.bbs.pojo.Vipconsumer;

public interface VipconsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipconsumer
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int deleteByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipconsumer
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insert(Vipconsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipconsumer
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int insertSelective(Vipconsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipconsumer
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    
    Vipconsumer selectByPrimaryKey(Integer vipid);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipconsumer
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKeySelective(Vipconsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipconsumer
     *
     * @mbggenerated Thu Jul 09 14:43:49 CST 2020
     */
    int updateByPrimaryKey(Vipconsumer record);
    
    List<Vipconsumer> search(Vipconsumer vipconsumer);
    List<Vipconsumer> cha(Vipconsumer vipconsumer);
}